# settings
PORT = 'COM4'
BAUD = 9600

W, H = 1000, 640

MAX_DIST = 50
MAX_TRAIL = 150

TITLE = "ARDUINO ULTRASONIC RADAR"
WINDOW_TITLE = f"Arduino Ultrasonic Radar"

# initials
INITIAL_ANGLE = 90.0
INITIAL_DISTANCE = 0.0